In [3]:
import numpy as np

# Eigenvalues and Eigenvectors


For a square matrix A:
1. Determinant of A equals the product of the eigenvalues
2. Trace of A equals the sum of the eigenvalues
3. If a is symmetric, all of its eigenvalues are real
4. If A is invertible. Then the eigenvalues of $A^{-1}$ are $\dfrac{1}{\lambda_i}$

In [8]:
A = np.array([[1,2],[2,1]])
# columns of evecs are eigenvectors of A
evals, evecs = np.linalg.eig(A)

# QR Decomposition
$A = QR$

- Q is an orthogonal matrix ($Q^TQ=I$)
- R is an upper triagular Matrix

If a square matrix A is nonsigular, then QR factorization is unique

In [16]:
def QR_Decomposition(A):
    """
    https://python.quantecon.org/qr_decomp.html
    
    QR decomposition is equivalent to Gram-Schmidt process (with Q as the resulting independent matrix)
    
    """
    
    n, m = A.shape
    
    Q = np.empty((n, n))
    u = np.empty((n, n))
    
    u[:, 0] = A[:, 0]
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])
    
    for i in range(1, n):
        u[:, i] = A[:, i]
        for j in range(i):
            # Gram-Schmidt process
            u[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j]
        Q[:, i] = u[:, i] / np.linalg.norm(u[:, i])
        
    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j] @ Q[:, i]
            
    return Q, R

A = np.array([[1.0, 1.0, 0.0], [1.0, 0.0, 1.0], [0.0, 1.0, 1.0]])
Q, R = QR_Decomposition(A)

# Singular Value Decomposition

Matrix **X** (m*n) of rank p
- n: sample
- m: attribution

$X = U\Sigma V^T$
- $UU^T=I$, $U^TU=I$
- $VV^T=I$, $V^TV=I$

In [1]:
import numpy as np
X = np.random.rand(5,2)
U, S, V = np.linalg.svd(X,full_matrices=True)  # full SVD
Uhat, Shat, Vhat = np.linalg.svd(X,full_matrices=False) # economy SVD
print('U, S, V =')
U, S, V

U, S, V =


(array([[-0.29186613,  0.65946664, -0.09420768, -0.6792746 ,  0.09812666],
        [-0.49908744, -0.33887884, -0.57264381, -0.11362608, -0.54336087],
        [-0.51143062, -0.2538992 ,  0.78739929, -0.16025057, -0.16821423],
        [-0.51935197,  0.48181491, -0.02660546,  0.70292526,  0.057586  ],
        [-0.36665807, -0.39198784, -0.20615158, -0.07675264,  0.81456611]]),
 array([1.34162221, 0.52158107]),
 array([[-0.71454801, -0.69958641],
        [ 0.69958641, -0.71454801]]))

# Numpy Implementation

## Broadcasting

- Step 1: When **dimensions** of two arrays do not match, Numpy will expand the one with fewer dimensions by adding dimensions on the left of the existing dimensions.
    
    I.E. a (3,2,2); b(2,). b will become (1,1,2)


- Step 2: When the two arrays have the same dimension but **different shapes**, Numpy will try to expand the dimension with shape 1
- Step 3: After Step 1 and 2, if two arrays still do not match, a ValueError will be raised.